development:
  adapter: mysql2
  database: ui_changed_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: ui_changed_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: ui_changed_prod
  username: root
  password:
  host: localhost