defaults: &defaults
  control_path: "public/screenshots/control/"
  test_path: "public/screenshots/test/"
  compare_path: "public/screenshots/compare/"
  selenium_browser: "firefox"
  auth_username:
  auth_password:
  control_url: "http://github.com"
  test_url: "http://github.com"
  skip_url_reg_exp: "(recipes|ingredients)"
  skip_query_strings: true
  email_results_to:
  email_after_control_crawl: true
  email_after_test_crawl: true
  email_after_compare: true
  email_after_compare_with_diffs: true
  email_after_compare_with_diffs_on_zero_found: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
